baseURL = "https://neon-empanada-c447cf.netlify.app/"
languageCode = "en-us"
title = "Notes for later"
theme = "digitalgarden"


[Params]
  description = "My Digital Garden on the Internet"
  images = ['/digital-garden-logo.png']
  enableSearch = true

[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'Content'
  params.header = true
  weight = 2
[[menu.main]]
  name = 'Articles'
  url = '/articles'
  weight = 3
[[menu.main]]
  name = 'Stack'
  url = '/stack'
  weight = 5


[[menu.social]]
  name = 'GitHub'
  url = 'https://github.com/JeromeDesseaux'
  weight = 1
[[menu.social]]
  name = 'LinkedIn'
  url = 'https://www.linkedin.com/in/jeromedesseaux/'
  weight = 2
[[menu.social]]
  name = 'Email'
  url = 'mailto:jerome.desseaux@skuld.fr'
  weight = 3
[[menu.social]]
  name = 'RSS'
  url = '/articles/index.xml'
  weight = 4


# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
