[build]
publish = "public"
command = "npm i && npm i -g postcss-cli && hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.106.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"